Configuratron:
  preload: True

use_gpu: False

datasets:
  sleepeeg:
    name: "EEG data"
    toplevel: /Volumes/SED/training/
    tmin: 0
    tlen: 6
    data_max: 0.001
    data_min: -0.001
    train_params:
      epochs: 7
      batch_size: 4
    lr: 0.0001
    folds: 5